### ISSUE TITLE
ChatGPT增加了cloudflare检测，cookies需要有 cf_clearance

### ISSUE THREAD

**Issue by oblank** [37iOS/iChatGPT#1]
RT

同时不知道为什么通过这种方式请求总比官方慢很多

非常好的项目，感谢

**Comment by iHTCboy** [comment]
> RT
> 
> 
> 
> 同时不知道为什么通过这种方式请求总比官方慢很多
> 
> 
> 
> 非常好的项目，感谢

@oblank 好的啊，感谢反馈，明天看看~

**Comment by iHTCboy** [comment]
v1.1.1 Cloudflare cookie support

https://github.com/37iOS/iChatGPT/releases
