### ISSUE TITLE
具体填写数据是？

### ISSUE THREAD

**Issue by 996WJC** [37iOS/iChatGPT#11]
session token，需要填写的是？
cf Clearance，需要填写的是？
user agent，需要填写的是？

我目前只有 open AI的API KEYS

**Comment by crazypoo** [comment]
> session token，需要填写的是？ cf Clearance，需要填写的是？ user agent，需要填写的是？
> 
> 我目前只有 open AI的API KEYS

https://github.com/crazypoo/PTChatGPT 这个可以帮你

**Comment by AlphaGogoo** [comment]
新版本只需要填写openaiKey就可以了，下载源码编译即可

**Comment by 996WJC** [comment]
> 新版本只需要填写openaiKey就可以了，下载源码编译即可

老师您说的下载源码进行编译，这个操作流程我估计还不太会，我并不是一个懂技术的程序员同学呢。我下载的版本是Mac端的应用，好像没有这个编译的，是吧

**Comment by iHTCboy** [comment]
@996WJC 你好，目前 2.0 版本已经支持 OpenAI API key，欢迎下载 https://github.com/37iOS/iChatGPT/releases
