### ISSUE TITLE
修改key之后不能马上生效

### ISSUE THREAD

**Issue by AlphaGogoo** [37iOS/iChatGPT#12]
在使用过程中偶然发现，修改key之后不能立刻生效，需要退出软件重启才可以，希望作者可以再完善一下

**Comment by iHTCboy** [comment]
@AlphaGogoo  thanks~ 2.0 版本，我已经修复了~

**Comment by AlphaGogoo** [comment]
> @AlphaGogoo thanks~ 2.0 版本，我已经修复了~

已更新，谢谢大佬

**Comment by iHTCboy** [comment]
@AlphaGogoo 👋
Thank you for submitting PR~
