### ISSUE TITLE
什么时候上架

### ISSUE THREAD

**Issue by AmingLMH** [37iOS/iChatGPT#13]
感谢大佬开发，求问什么时候能够上架AppStore😁

**Comment by iHTCboy** [comment]
@AmingLMH 你好，感谢支持。目前送审 TestFlight 版本，需要看苹果的审核结果在决定是否可以上架 App Store 😁。

**Comment by iHTCboy** [comment]
@AmingLMH 现在 iOS可以通过 TestFlight下载

名额有限，先下先得！

下载地址：https://testflight.apple.com/join/GR4BOt2M

![image](https://user-images.githubusercontent.com/11418363/225786313-bb957b26-62da-40c4-88a7-38faeb22cfab.png)
