### ISSUE TITLE
提两个UX的小建议

### ISSUE THREAD

**Issue by wyk111wyk** [37iOS/iChatGPT#14]
1. 希望可以自由的选择并且复制答案的文字，尤其是代码部分，在代码上加个复制的按钮也行。但最好是文字选择。
<img width="638" alt="截屏2023-03-16 13 44 21" src="https://user-images.githubusercontent.com/8171481/225525756-7e0eff02-0f17-4975-8d7b-1e20f351edcd.png">
2. 希望可以在确定后，页面自动定位到最低点，将答案完整的显示。

**Comment by iHTCboy** [comment]
@wyk111wyk 好的，感谢反馈，后续版本优化迭代，也欢迎提PR，一起完善~😁

**Comment by iHTCboy** [comment]
@wyk111wyk 

iOS / iPadOS / macOS(M1/M2) TestFlight Downlad：https://testflight.apple.com/join/GR4BOt2M
Intel Mac Download: https://github.com/37iOS/iChatGPT/releases/download/2.3/iChatGPT-macOS-v2.3.zip

**v2.3 Update(更新):**

- New conversation feature added. (新增对话功能)
- Conversation records can now be saved. (支持对话记录存档)
- Added historical conversation switching feature. (增加历史对话切换功能)
- Improved conversation list experience with the ability to quickly scroll to the top or bottom. (改善对话列表体验，可快速滚动到顶部或底部)
- Option to request conversations without historical records (toggleable through an icon on the left side of the input box). (新增对话记录选项，可选择是否携带历史记录进行请求（通过输入框左侧的图标进行切换）)
- Added support for additional languages including Traditional Chinese, Korean, Japanese, French, German, and Russian. (支持更多语言（包括繁体中文、韩语、日语、法语、德语、俄语等）)

**Upcoming features preview（即将推出的功能预览）:**

- Language input support. (支持语言输入)
- Custom API URL support. (支持自定义 API URL)
- Exporting images or PDFs for sharing. (支持导出图片或 PDF 分享)
- Code highlighting and copying support. (支持代码高亮和复制等)
- Table display support. (支持表格显示)
- Stream output support. (支持流式输出)
- Custom icon support. (支持自定义图标)
- Etc. (等)
