### ISSUE TITLE
【增强】希望能增加选择模型的功能，允许切换 GPT-3.5、GPT-4

### ISSUE THREAD

**Issue by ypwhs** [37iOS/iChatGPT#17]
希望能增加选择模型的功能，允许切换 GPT-3.5、GPT-4。

**Comment by iHTCboy** [comment]
@ypwhs 收到，好的，我们后续版本增加~

**Comment by iHTCboy** [comment]
@ypwhs 最新代码已经支持切换  GPT-3.5、GPT-4。

TestFlight 版本也支持 gpt-4

名‮有额‬限，先下先得！

下载地址：https://testflight.apple.com/join/GR4BOt2M
