### ISSUE TITLE
Mac端填入Session Token信息保存后、提问报错403

### ISSUE THREAD

**Issue by rxg9527** [37iOS/iChatGPT#2]
Mac客户端版本v1.1.2，按照Readme和如图操作后，报错「非预期的响应内容:  HTTP:403」
报错HTML渲染后，内容是
# chat.openai.com

## Checking if the site connection is secure

chat.openai.com needs to review the security of your connection before proceeding.

Ray ID: `7793b967cb9e9e6e`

Performance & security by [Cloudflare](https://www.cloudflare.com?utm_source=challenge&utm_campaign=m)

![Snipaste_2022-12-14_11-06-26](https://user-images.githubusercontent.com/11425983/207496169-5767e0a1-7c8e-4c2f-b663-c68640a7228b.png)

**Comment by iHTCboy** [comment]
@rxg9527 你好。这个是 ChatGPT 机制，会检查您的 IP 地址和用户代理的绑定，目前session有效期为 2 小时。

你填写好后，重新打开 app 试试，我这个测试重新打开就可以。目前 ChatGPT 防机器人的机制不断变化，而且通过官网访问也不稳定，所以可能体验没有之前好😅

**Comment by rxg9527** [comment]
@iHTCboy 谢谢解答。昨天试了下还是有问题，可能是网络IP的原因。等一个正式API😂

**Comment by crazypoo** [comment]
GG,只能夠用網頁版去做實驗

**Comment by iHTCboy** [comment]
@rxg9527 你好，目前 2.0 版本已经支持 OpenAI API key，欢迎下载 https://github.com/37iOS/iChatGPT/releases
