### ISSUE TITLE
能提供给我一个key吗？

### ISSUE THREAD

**Issue by goushine** [37iOS/iChatGPT#20]
我想尝试下移动端使用GPT，我懂一些HCI，遇到交互方便的问题我会及时反馈。

**Comment by iHTCboy** [comment]
> 我想尝试下移动端使用GPT，我懂一些HCI，遇到交互方便的问题我会及时反馈。

你好，感谢支持。非常抱歉，为了响应国内政策或法规，我们不提供帐号或密钥服务，开源项目只供研究和学习。

注册帐号可参考文章：https://mp.weixin.qq.com/s/bORmmiIxwFvg0IkN_wUDVQ
