### ISSUE TITLE
希望可以添加自定义api url的功能

### ISSUE THREAD

**Issue by Tongzhao9417** [37iOS/iChatGPT#23]
由于梯子的原因，一些用户可能无法直接访问api.openai.com的网址。可以通过CF代理的方式进行访问。如果能进行自定义url，那么就可以更方便的使用自己的API

**Comment by iHTCboy** [comment]
@Tongzhao9417 好的，感谢反馈意见，后继版本可开发添加啊

**Comment by kakahu2015** [comment]
我也强烈希望支持自定义API url

**Comment by iHTCboy** [comment]
@Tongzhao9417 @kakahu2015  v2.6 版本已经增加自定义API url

**Downlad：**
- iOS / iPadOS / macOS(M1/M2) TestFlight Downlad：https://testflight.apple.com/join/GR4BOt2M
- Intel Mac Download: https://github.com/37iOS/iChatGPT/releases/download/2.6/iChatGPT-macOS-v2.6.zip

**Update：**
- Support custom API URL.（支持自定义 API URL。）
- Set API timeout duration.（设置 API 超时时间。）
- Configure API model for individual chat rooms.（支持聊天室单独设置 API 模型。）
- Support more model choices (e.g., gpt-4-32k).（支持更多模型选择，如 gpt-4-32k 等。）
- Change icons to local images and differentiate gpt-4 icons.（将图标更改为本地图片并区分 gpt-4 图标。）
- Fix auto letter conversion issue with consecutive characters (e.g., in Chinese or Japanese).（修复连续输入字符时自动变为字母的问题，如中文或日文。）

**Comment by Jasonsey** [comment]
@iHTCboy 您提到的自定义URL是API HOST，实际上大家更需要的是完整的，例如: `http://api.openai.com/v1`这种类型的自定义。毕竟大家做了转发之后不一定能做到https。

另外，我检查了OpenAI这个Swift库，它也只是支持自定义host，我感觉您可能需要做一部分定制才行：https://github.com/MacPaw/OpenAI/issues/27
