### ISSUE TITLE
未能读取设置，数据缺失

### ISSUE THREAD

**Issue by mikejzy** [37iOS/iChatGPT#27]
![image](https://user-images.githubusercontent.com/51266514/226674175-1e40d487-33b7-40d4-af3c-af23c30c6acc.jpeg)

请教为何？

**Comment by iHTCboy** [comment]
@mikejzy 你好，需要设置OpenAI 的 API Key 才能使用

**Comment by mikejzy** [comment]
已经设置apik

**Comment by iHTCboy** [comment]
@mikejzy 现在可以了吗

**Comment by iHTCboy** [comment]
可以打开页面 https://platform.openai.com/account/usage，查看一下当前账号余额是否有效和足够啊：

![image](https://user-images.githubusercontent.com/11418363/227691908-8e29b0f9-9a96-43ee-a687-e4d0ed2ee2ee.png)

**Comment by AbnerPei** [comment]
2024.05.23下载，已配置API Key，用的3.5，依然这个错，怎么解决？
