### ISSUE TITLE
可以实现逐字输出效果吗

### ISSUE THREAD

**Issue by Louis-XWB** [37iOS/iChatGPT#28]
一次性输出全部内容会感觉中间没有任何结果的等待时间比较长，谢谢

**Comment by iHTCboy** [comment]
@Louis-XWB 现在接口是一次返回内容，可能没有必要逐字输出。有其它接口可以实现部分答案返回吧？

另外，是因为每次请求都把之前的提问和问答带上，导致请求慢，v2.2 版本已经优化。稍等可以更新~
