### ISSUE TITLE
在Mac端无法通过滚轮实现上下滑动

### ISSUE THREAD

**Issue by AlphaGogoo** [37iOS/iChatGPT#29]
在Mac端无法通过滚轮实现上下滑动，只能像手机那样点击拖动才行

**Comment by iHTCboy** [comment]
> 在Mac端无法通过滚轮实现上下滑动，只能像手机那样点击拖动才行

iOS 兼容包在 M1上是只能拖。 Mac 版本不太清楚，我没有滚轮的鼠标。

🤩用苹果触摸板或苹果鼠标是可以滑动。

**Comment by AlphaGogoo** [comment]
> 



> > 在Mac端无法通过滚轮实现上下滑动，只能像手机那样点击拖动才行
> 
> @AlphaGogoo iOS 兼容包在 M1上是只能拖。 Mac 兼容的版本不太清楚，我没有滚轮的鼠标。
> 
> 🤩用苹果触摸板或苹果鼠标是可以滑动。

触控板也不可以

**Comment by iHTCboy** [comment]
@AlphaGogoo 你是用 TestFlight 下载的版本吗，我测试  Mac M1 macOS 13.0.1 上可以啊

**Comment by AlphaGogoo** [comment]
> @AlphaGogoo 你是用 TestFlight 下载的版本吗，我测试 Mac M1 macOS 13.0.1 上可以啊

用了TestFlight下载的可以了，不过不知道为啥我用源码编译的不可以

**Comment by iHTCboy** [comment]
@AlphaGogoo 源码的话，需要选择 buid iOS  ipa，如果是 Mac Catalyst 会以 Mac 的方式继承。

<img width="355" alt="image" src="https://user-images.githubusercontent.com/11418363/227431361-58d9ff23-e119-47a4-8301-424ea6aaba79.png">
