### ISSUE TITLE
gpt-4 还不能使用么？ "未能读取数据，因为数据丢失。"，切换到3.5就可以用。

### ISSUE THREAD

**Issue by qq432591** [37iOS/iChatGPT#31]

**Comment by iHTCboy** [comment]
@qq432591 因为没有GPT4权限，官方文档显示，4和3.5接口是一样的，这个问题不清楚GPT4 key不一样吗，明天确认一下啊🤩

**Comment by iHTCboy** [comment]
@qq432591 目前官方文档显示 https://platform.openai.com/docs/models/gpt-4 还是限制性内测，需要加入等待列表 [join the waitlist](https://openai.com/waitlist/gpt-4)，需要确认一下你是否获取了 gpt-4 的测试权限啊

![image](https://user-images.githubusercontent.com/11418363/227690469-baafc94f-f875-4800-9b97-984c7ed6b3c8.png)
