### ISSUE TITLE
Getting « The data couldn’t be read because it is missing.»

### ISSUE THREAD

**Issue by Bogdan0w** [37iOS/iChatGPT#32]
Hey, I’m getting “ The data couldn’t be read because it is missing.” error when I request a question. I can type anything in input field, but will always get that error. API key is set, so it’s not problem with the API key.

![23A031F3-523C-4D24-A130-04E95518FD80](https://user-images.githubusercontent.com/53834256/227477992-82a93bd4-286c-4fe3-b577-6b57fdfec827.png)

**Comment by iHTCboy** [comment]
@Bogdan0w This sentence is the error message returned by OpenAI Api, which means that there is no problem with your network. From experience, your KPI key may be filled in incorrectly, or the account is in arrears, etc. You can check it.

**Comment by Bogdan0w** [comment]
I have tried to re-generate API key and used another account, nothing helps

**Comment by iHTCboy** [comment]
> I have tried to re-generate API key and used another account, nothing helps 

@Bogdan0w Hello, I’m very sorry. Can you reinstall the app to see if it‘s solved? Or if you can, provide me with key to assist in the investigation, ihetiancong@gmail.com or twitter @iHTCboy, thank you for your feedback~
