### ISSUE TITLE
答案字数是受限制吗？

### ISSUE THREAD

**Issue by wasabia99** [37iOS/iChatGPT#34]
与网页端回答不一样 且字数短

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by iHTCboy** [comment]
@wasabia99 有参数可调，现在是默认值。后继版本增加自定义参数啊

**Comment by iHTCboy** [comment]
@wasabia99 已经增加了 Temperature 字段配置，默认值为 0.7，取值 0-2。值越大，每次返回的结果越随机，即相似度越小。值越小，生成的文本越相似。

### [v2.5](https://github.com/37iOS/iChatGPT/releases/latest)

**Update：**
- Added chat room settings with Prompt and Temperature parameter configuration. (新增聊天室设置功能，支持 Prompt 和 Temperature 参数配置。)
- Display current conversation identifier in the history list. (历史对话列表增加显示当前对话标识。)
- Fixed potential crash when sending conversations. (修复发送对话时可能会崩溃的问题。)
- Removed restrictions on creating new conversations and switching history when requesting a conversation. (请求对话时，取消创建新对话和切换历史对话的禁用限制。)
- Improved multi-language translations for sharing feature. (完善分享功能的多语言翻译。)

**Downlad：**
- iOS / iPadOS / macOS(M1/M2) TestFlight Downlad：https://testflight.apple.com/join/GR4BOt2M
- Intel Mac Download: https://github.com/37iOS/iChatGPT/releases/download/2.5/iChatGPT-macOS-v2.5.zip
