### ISSUE TITLE
支持prompt模板

### ISSUE THREAD

**Issue by zhongsheng94** [37iOS/iChatGPT#36]
### 能否支持使用prompt模板

比如当用户输入`keyword`，向ChatGPT发送 `你认为${keyword}是什么原因？你是从哪里了解到的？能给我一些关于它的链接吗？`

**Comment by crazypoo** [comment]
@zhongsheng94 要不用我的吧,你的这些需求我早就开源了 https://github.com/crazypoo/PTChatGPT,lol

**Comment by iHTCboy** [comment]
@zhongsheng94 好的，近期版本会更新支持。

iOS / iPadOS / macOS(M1/M2) TestFlight Downlad：https://testflight.apple.com/join/GR4BOt2M
Intel Mac Download: https://github.com/37iOS/iChatGPT/releases/download/2.3/iChatGPT-macOS-v2.3.zip

**v2.3 Update(更新):**

- New conversation feature added. (新增对话功能)
- Conversation records can now be saved. (支持对话记录存档)
- Added historical conversation switching feature. (增加历史对话切换功能)
- Improved conversation list experience with the ability to quickly scroll to the top or bottom. (改善对话列表体验，可快速滚动到顶部或底部)
- Option to request conversations without historical records (toggleable through an icon on the left side of the input box). (新增对话记录选项，可选择是否携带历史记录进行请求（通过输入框左侧的图标进行切换）)
- Added support for additional languages including Traditional Chinese, Korean, Japanese, French, German, and Russian. (支持更多语言（包括繁体中文、韩语、日语、法语、德语、俄语等）)

**Upcoming features preview（即将推出的功能预览）:**

- Language input support. (支持语言输入)
- Custom API URL support. (支持自定义 API URL)
- Exporting images or PDFs for sharing. (支持导出图片或 PDF 分享)
- Code highlighting and copying support. (支持代码高亮和复制等)
- Table display support. (支持表格显示)
- Stream output support. (支持流式输出)
- Custom icon support. (支持自定义图标)
- Etc. (等)

**Comment by iHTCboy** [comment]
@zhongsheng94 @crazypoo   v.25 已经增加 Prompt 设置。

### [v2.5](https://github.com/37iOS/iChatGPT/releases)

**Update：**
- Added chat room settings with Prompt and Temperature parameter configuration. (新增聊天室设置功能，支持 Prompt 和 Temperature 参数配置。)
- Display current conversation identifier in the history list. (历史对话列表增加显示当前对话标识。)
- Fixed potential crash when sending conversations. (修复发送对话时可能会崩溃的问题。)
- Removed restrictions on creating new conversations and switching history when requesting a conversation. (请求对话时，取消创建新对话和切换历史对话的禁用限制。)
- Improved multi-language translations for sharing feature. (完善分享功能的多语言翻译。)

**Downlad：**
- iOS / iPadOS / macOS(M1/M2) TestFlight Downlad：https://testflight.apple.com/join/GR4BOt2M
- Intel Mac Download: https://github.com/37iOS/iChatGPT/releases/download/2.5/iChatGPT-macOS-v2.5.zip
