### ISSUE TITLE
TextView not support Chinese

### ISSUE THREAD

**Issue by OhMrWhite** [37iOS/iChatGPT#37]
https://github.com/SwiftUIX/SwiftUIX/issues/160

**Comment by iHTCboy** [comment]
@OhMrWhite 收到，感谢反馈。这个问题是 SwiftUIX 没有兼容 TextView，会提反馈让它修复啊

**Comment by iHTCboy** [comment]
@OhMrWhite v2.6 已经修复：

**Downlad：**
- iOS / iPadOS / macOS(M1/M2) TestFlight Downlad：https://testflight.apple.com/join/GR4BOt2M
- Intel Mac Download: https://github.com/37iOS/iChatGPT/releases/download/2.6/iChatGPT-macOS-v2.6.zip

**Update：**
- Support custom API URL.（支持自定义 API URL。）
- Set API timeout duration.（设置 API 超时时间。）
- Configure API model for individual chat rooms.（支持聊天室单独设置 API 模型。）
- Support more model choices (e.g., gpt-4-32k).（支持更多模型选择，如 gpt-4-32k 等。）
- Change icons to local images and differentiate gpt-4 icons.（将图标更改为本地图片并区分 gpt-4 图标。）
- Fix auto letter conversion issue with consecutive characters (e.g., in Chinese or Japanese).（修复连续输入字符时自动变为字母的问题，如中文或日文。）
