### ISSUE TITLE
有没有非官方API的  access token逆向调用方式，apikey额度用完了都

### ISSUE THREAD

**Issue by gsons** [37iOS/iChatGPT#38]
有没有非官方API的  access token逆向调用方式，apikey额度用完了都。类似这些项目 https://github.com/acheong08/ChatGPT ；https://github.com/moeakwak/chatgpt-web-share；

**Comment by gsons** [comment]
额 有没有提供未签名的ipa包下载一下，我这边可以用trollstore直接安装

**Comment by iHTCboy** [comment]
> 有没有非官方API的 access token逆向调用方式，apikey额度用完了都。类似这些项目 https://github.com/acheong08/ChatGPT ；[https://github.com/moeakwak/chatgpt-web-share；](https://github.com/moeakwak/chatgpt-web-share%EF%BC%9B)

你好，我们不提供 token

**Comment by iHTCboy** [comment]
> 额 有没有提供未签名的ipa包下载一下，我这边可以用trollstore直接安装

@gsons 好的，今天发版会打一个。

**Comment by iHTCboy** [comment]
@gsons 这个可以下载 ipa https://github.com/37iOS/iChatGPT/releases/download/2.4/iChatGPT-v2.4.ipa

https://github.com/37iOS/iChatGPT/releases

**Comment by gsons** [comment]
@iHTCboy  可以了，我用trollstore装上了，感谢🙏
