### ISSUE TITLE
提示403

### ISSUE THREAD

**Issue by Zero-Cjh** [37iOS/iChatGPT#4]
按照提示填入对应参数后，还是一直显示这个
能提供一下解决方案吗，iOS和macOS都是一样的错误
非预期的响应内容:  <r>HTTP:403</r> <!DOCTYPE html>
<html lang="en-US">
<head>
    <title>Just a moment...</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="robots" content="noindex,nofollow">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="/cdn-cgi/styles/challenges.css" rel="stylesheet">
    

</head>
<body class="no-js">
    <div class="main-wrapper" role="main">
    <div class="main-content">
        <h1 class="zone-name-title h1">
            <img class="heading-favicon" src="/favicon.ico"
                 onerror="this.onerror=null;this.parentNode.removeChild(this)">
            chat.openai.com
        </h1>
        <h2 class="h2" id="challenge-running">
            Checking if the site connection is secure
        </h2>
        <noscript>
            <div id="challenge-error-title">
                <div class="h2">
                    <span class="icon-wrapper">
                        <div class="heading-icon warning-icon"></div>
                    </span>
                    <span id="challenge-error-text">
                        Enable JavaScript and cookies to continue
                    </span>
                </div>
            </div>
        </noscript>
        <div id="trk_jschal_js" style="display:none;background-image:url('/cdn-cgi/images/trace/managed/nojs/transparent.gif?ray=77a580da7dd9c0f2')"></div>
        <div id="challenge-body-text" class="core-msg spacer">
            chat.openai.com needs to review the security of your connection before proceeding.
        </div>
        <form id="challenge-form" action="/backend-api/conversation?__cf_chl_f_tk=eqbiscIqbM7dkjMCb.2wgrHHb3FTjuRpwRdHtYNWaKc-1671173620-0-gaNycGzNB70" method="POST" enctype="application/x-www-form-urlencoded">
            <input type="hidden" name="md" value="FdRaNwt95OO_guDcTdMWfamTdlyRIx2ZDXdBs.myDVE-1671173620-0-AZ4C6YGiqJgtvn82eVi_723YF5RrU4BnhHeyGIeUtErQeivoYxg3zQmZEnOjGQJhPL4YKdt7O3J3_aTnI4ADsYTXWZ1Iyq1aOcXB1_iVm4aQ4LkYglmmy2aJHsdRiZVQEl7DvZ3lzmJjbgOUigLl0f_gHiHmw8hTAMmeTj2Z3umWXPs81A1KTpVBwOZoFyOp12-1IAOTERdKKvxVJj1UGAFFVDu0g9sWMgz_MANg08bkgSX4l_pEEA6qLSut-kTdIX8zHzxfqn3NsPLcs_4F0oaIAxMgcJiKwMVR8YrXXTzm4Wtf7_SdQdtVL95scaJUMrfIZE_t5fzCj1s6o658C54Z1vdqdibmwTjS4Dw0PjtOC11lEgqAHOQSr4vOA3PlGHCDBRHAcQtowb3fBs4v8FPPMy7GkjjcUtsB-Nb3lQeyNQV5060pPuwPE-aAsx9Cod8YWDZN_taPk3C0YOXwCPjmrk-syXhj5qLOeSu0Mhr2m0rIM11uo3IHgwvIuu5CWNkaZ1GiQfJyfXOEkGxyWSI6n3E4NAIbiEfz-BNcVGQoFHQ3Nf71VYZ_xx-7GsT_VTlqnzjjumvrwCEJ7glbfL83KgUHzq3eZH4oU-ThBaIUvow3vrRRbx4IbzFXH74vD7Aaq2ToFimOh_6ZDN_0M12q48EAdvd2-hBJ9a5qE3Mak9CI_wQnVc1gYkokSjhtyg">
            <input type="hidden" name="r" value="_7HzGHKQgjRnGnr0MXK.4YyANjPhKhVe_qufAIxLCO0-1671173620-0-AagKcH+bXC7W0RUhS+XzC8CbE6hFf2idcEoI/fUHOKIVnHS1NVRo5ZU+u8uXZAYZ6aAr2+faHSKfZ6sZ0N41/RYOMedj3JuaMvRj1u9nNsJ4RjhY3sThWnGCGs1JQH+NO4D3NEzzu8Vr2PkQc/dtgqp83fkgb8FuWzJrovJcPUNOi+TxeoCCh8KqVDJqD8lF4kL6PYLqqViS0M1r53pXOhTDiY2NFzCvyjPRtLDyWgCPmRdbT1Ec7OxfrWysyOUX5qsNjGb/BDN8IguafJ9jiIMWict0lZUA4/rTOKBvgiGK347POo0FHslapMYW9F8ZU+p9yxVW4O7vj1cYD7knpjQSexaA5Zfy8rNIED8VJWDPzlEFqEF4m7x01mBqu0WdptjRsWETH+qWP21C23JNGM2sDkFShT1WTdk3sdMCfYcjNFoapbj8ahJDjlJGwb+4/7k96NxNLZf9fvcdSUAQ5rwulLlO5plBV5JOHqUusbKnq1x3+M5FcqAxL8cFc2+j7yQlBaLF35AFti38xVHUe09iFOj+mO1yUb8eCInALvCX0JAanh2M2A6TQB568qAsIIP+zIv+Qang94cHEpsHFc2xVwy3oBzlr2DaTzYuhJbIGNolMIfXWhHRqtz0McFqlD9TiAkrG8lqv+68LEAuqItZCBy46zxAUV+zzlMwOCUkP8M+BWla1Yd8A5bWb9z1eDmDn0UHn4M35pG9HtPNccKYyIIheLyQA4mFfZgmTPa6kuwpldIaphxk5O/baJuCw5pGCRjhIctL2Oh+E5PRovgXYt4H720FTexCwa8O2T3jgiEJ6Ya0hwE5CQI06InQpQ2Q6BxTboUey8C8S9OLjCrwBQTkLGn2CoYIILyqeh3+aKl2l7HmEBea7PBnB+xCWmfrNPkztWLLc1I3pE+3arB2lj/aauxXrM7moT2gCW9AartZyys6J2g4Ba7Kw769YepSLI2BaKETaIO+Ne1Ic06CYgZJ7+BvQAu2ZIRk6WslFm4NU/baE9sHzgNeyOY2Fm5BveJcuSBSsK9ibgSalG8ba32qayB/ssdw5C5g104xDB0jQdW/uqDrz4WOQsU1BSyrZHORS+ckWzfU7lMexXOO97s4Xp2ASz+G+O6PrespiqseYrrstt2Q+UuE3x732V45evgOSOrzHo4P8NYx3iL+PUv1vtOUfc7E/NBc6R3C7O3u0KG7deAOx3azfKCgkgHRawXIpnbDahnjCQKt4jDzHVIKvd5G+Urd33o/4MkNHmZ4so0qai4cLttSISe7FYFxBNVS3bmjeo43GCbweiqCDf3TNORNJUVimGW8iet2Ct0yluXSbvEOMiWrfYiDbGP8yYBrdw1OQ3dxDElLAz77L7vP6avaAWz0QUbTgMAo77jOnQ3P37rp53nbdK27AS0gt5BVyqMqPft9Fg8pcDMtO3DQM0UU/6zxBdShWHD/uzStR7yXwGZa2HTtQr/G6gLroQH4jl1yONFqE5oHuAdvljBAEnuw4bp2IDiv//3z3voaL2EwprTk+MJUlyYulpCmNjBBCvklc0zMY9DHghzrQuroxI+rXJy+Xep8q4HeuCzPoqHdcXqSVH7C3wIBIejdc6IpThUBAGnUcHQVdvJe9WC5V2XukoHh8xuY/51lNYk8rRLsRMX4eNbRfR1b3DfmM1X9DOzh6y6i8NUWG1I/jNvgQ53k5UZHPSKg2Am31NttyS+YKry9W1CcQVCADsdDLfLz+Lm0stYM/dGxJQ+tP7WYWmZaJXx51D+MgtIk/Vrsx+wfT3iX+wni7WXI2hbHIY5pfR2OqHT3+h2dzge77M2cGpsGKcmNvAR5KTtQe3olBOP5W6AHMrHH2XH787ETQh+02vAKeU2ovcwQuSO8MFfjke18PZdR/jz8/oC7UoQnngkPHEZEvX08KhgxRg==">
        </form>
    </div>
</div>
<script>
    (function(){
        window._cf_chl_opt={
            cvId: '2',
            cType: 'managed',
            cNounce: '52725',
            cRay: '77a580da7dd9c0f2',
            cHash: '430a42f451f04dd',
            cUPMDTk: "\/backend-api\/conversation?__cf_chl_tk=eqbiscIqbM7dkjMCb.2wgrHHb3FTjuRpwRdHtYNWaKc-1671173620-0-gaNycGzNB70",
            cFPWv: 'g',
            cTTimeMs: '1000',
            cTplV: 4,
            cTplB: 'cf',
            cRq: {
                ru: 'aHR0cHM6Ly9jaGF0Lm9wZW5haS5jb20vY2hhdC9iYWNrZW5kL2FwaS9jb252ZXJzYXRpb24=',
                ra: 'TW96aWxsYS81LjAgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbzsgY29tcGF0aWJsZTsgR29vZ2xlYm90LzIuMTsgK2h0dHA6Ly93d3cuZ29vZ2xlLmNvbS9ib3QuaHRtbCkgQ2hyb21lLzEwOC4wLjAuMCBTYWZhcmkvNTM3LjM2',
                rm: 'UE9TVA==',
                d: 'OU3DJks/qHpDe7xpGmo7WafN77JfVT87f4e3nKYJCWAmU3jeEfz0xmerGdTbyqgb/mnORLKuHSHRQJEEvpo1HyHcvk7/3gG+w3k44QYA6fnN7rxJBjwnmgrsA57Y/uoY1vlI3sVwO17FOymZyb58LrkOzh4Sp+c2KuPZ4xIymUf3N8kUp9tQucoliudQtv6YS0aTh4731GBgfHZ16s4J8oSlA9V/fPdFZqFTZjx1dv9igEo4gRv9z+TDN9gPEb6JtO9Qp+T5XwbLPvtoHs1OvXSpGXAHcBR3gMkCt5tpj45y31rYpl+WArycvmrrGBtpPrGHwfcjQ184CHoG9TRIMwTezXqkj7vIcqSDcVm0VvDratUSYMev8wytNSjfD8WvR/4LRQvwhmZ9SlFJh2hS0UWIS0laGriVR9A5fLD/ZEA6ZhwNWGqtzLxKbKI2Vle0AOB5e28Us+qMV+pQHwE+D0xYY9nQ2hcqELgNo89Z3nbZYqp+opP03nS1Pf0Z9sUKcg1OaLNeXghQnbVFbDaR5L3ulgvymi0+oNfGhD7SgmYNw/6Ds2vWnXLt7PjGST7IHeYSmpx+EHOd4avELTzi1LUmnUxaQ15CUy5JVodD6U8uPVneiiqGcQ8HXOiGm6UT5/3l9LLkDDXFsL8XAaXrhg==',
                t: 'MTY3MTE3MzYyMC44OTEwMDA=',
                m: 'PouhuSG4M7kV0GHKgwTxwcKei7bujDC0lffSBqU5s1w=',
                i1: '/gm/rLMQaQatTm1YM0y8YA==',
                i2: '5H/iS+KVOJlNQOyCgg6U0w==',
                zh: 'iuyN59AGNgeBFFEOPj72EN+xtBfXXvoCyd1dJnIVFAc=',
                uh: 'w+NeOS2eM6319mStwCUvaYmRm9BS2ZQKAp45tqudIII=',
                hh: 'foaWmAUHGGlVCZaNUJIHhxzxFNzSPNnVe6rJjiQw728=',
            }
        };
        var trkjs = document.createElement('img');
        trkjs.setAttribute('src', '/cdn-cgi/images/trace/managed/js/transparent.gif?ray=77a580da7dd9c0f2');
        trkjs.setAttribute('style', 'display: none');
        document.body.appendChild(trkjs);
        var cpo = document.createElement('script');
        cpo.src = '/cdn-cgi/challenge-platform/h/g/orchestrate/managed/v1?ray=77a580da7dd9c0f2';
        window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;
        window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, -window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;
        if (window.history && window.history.replaceState) {
            var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;
            history.replaceState(null, null, "\/backend-api\/conversation?__cf_chl_rt_tk=eqbiscIqbM7dkjMCb.2wgrHHb3FTjuRpwRdHtYNWaKc-1671173620-0-gaNycGzNB70" + window._cf_chl_opt.cOgUHash);
            cpo.onload = function() {
                history.replaceState(null, null, ogU);
            };
        }
        document.getElementsByTagName('head')[0].appendChild(cpo);
    }());
</script>

    <div class="footer" role="contentinfo">
        <div class="footer-inner">
            <div class="clearfix diagnostic-wrapper">
                <div class="ray-id">Ray ID: <code>77a580da7dd9c0f2</code></div>
            </div>
            <div class="text-center">Performance &amp; security by <a rel="noopener noreferrer" href="https://www.cloudflare.com?utm_source=challenge&utm_campaign=m" target="_blank">Cloudflare</a></div>
        </div>
    </div>
</body>
</html>

**Comment by xuebusi** [comment]
这个问题解决了吗？我的也是，mac和手机都一样！

**Comment by crazypoo** [comment]
> 这个问题解决了吗？我的也是，mac和手机都一样！

我把api封裝好了,填寫token就可以了https://github.com/crazypoo/PTChatGPT

**Comment by iHTCboy** [comment]
@Zero-Cjh  @xuebusi  你好，目前 2.0 版本已经支持 OpenAI API key，欢迎下载 https://github.com/37iOS/iChatGPT/releases
