### ISSUE TITLE
用拼音输入法时无法打出连续的两个汉字，会自动变成字母

### ISSUE THREAD

**Issue by wasabia99** [37iOS/iChatGPT#41]
<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by iHTCboy** [comment]
@wasabia99 收到，这个问题跟 https://github.com/37iOS/iChatGPT/issues/37 是一样，我打算给 [SwiftUIX](https://github.com/iHTCboy/SwiftUIX) 提个 PR, 或者使用 Fork 的分支先解决，这2天在更新一下版本啊

**Comment by iHTCboy** [comment]
@wasabia99  v2.6 已经修复：

**Downlad：**
- iOS / iPadOS / macOS(M1/M2) TestFlight Downlad：https://testflight.apple.com/join/GR4BOt2M
- Intel Mac Download: https://github.com/37iOS/iChatGPT/releases/download/2.6/iChatGPT-macOS-v2.6.zip

**Update：**
- Support custom API URL.（支持自定义 API URL。）
- Set API timeout duration.（设置 API 超时时间。）
- Configure API model for individual chat rooms.（支持聊天室单独设置 API 模型。）
- Support more model choices (e.g., gpt-4-32k).（支持更多模型选择，如 gpt-4-32k 等。）
- Change icons to local images and differentiate gpt-4 icons.（将图标更改为本地图片并区分 gpt-4 图标。）
- Fix auto letter conversion issue with consecutive characters (e.g., in Chinese or Japanese).（修复连续输入字符时自动变为字母的问题，如中文或日文。）
