### ISSUE TITLE
点击钥匙🔑无反应

### ISSUE THREAD

**Issue by dingge9527** [37iOS/iChatGPT#43]
输入不了钥匙

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by iHTCboy** [comment]
@dingge9527 你好，请问你是用什么设备和系统版本啊，测试 iOS 14.5 15.5 16.4 没问题，理论上都兼容🤔

**Comment by seagull13** [comment]
我的也没用 ios 14.0 iphone 11  点击右上角的钥匙一直没反应
