### ISSUE TITLE
Not English

### ISSUE THREAD

**Issue by skythunder2020** [37iOS/iChatGPT#5]
I can't read this

**Comment by iHTCboy** [comment]
@skythunder2020 Thanks for the reply, we will add English support in the next version 🤩

**Comment by iHTCboy** [comment]
@skythunder2020 Hello, the current version 2.0 already supports OpenAI API key. Welcome to download： https://github.com/37iOS/iChatGPT/releases

**Comment by iHTCboy** [comment]
@skythunder2020  New version 2.1 support English language!

iOS/ Mac M1/M2 :  TestFlight：https://testflight.apple.com/join/GR4BOt2M

Mac (Intel CPU)：https://github.com/37iOS/iChatGPT/releases
