### ISSUE TITLE
chat streaming

### ISSUE THREAD

**Issue by icstyledev** [37iOS/iChatGPT#51]
.

**Comment by iHTCboy** [comment]
@icstyledev v2.7 已经支持流式输出~

**Downlad：**
- iOS / iPadOS / macOS(M1/M2) TestFlight Downlad：https://testflight.apple.com/join/GR4BOt2M
- Intel Mac Download: https://github.com/37iOS/iChatGPT/releases/download/2.7/iChatGPT-macOS-v2.7.zip
