### ISSUE TITLE
能否添加api接入支持？

### ISSUE THREAD

**Issue by gdzhujun** [37iOS/iChatGPT#6]
能否添加api接入支持？

**Comment by iHTCboy** [comment]
好的，感谢反馈，我们研究一下~

**Comment by crazypoo** [comment]
> 能否添加api接入支持？

此客戶端可以支持api https://github.com/crazypoo/PTChatGPT

**Comment by iHTCboy** [comment]
@gdzhujun 你好，目前 2.0 版本已经支持 OpenAI API key，欢迎下载 https://github.com/37iOS/iChatGPT/releases
