### ISSUE TITLE
为什么无法访问这个https://chat.openai.com/chat,这个cookies该如何获取

### ISSUE THREAD

**Issue by XiaBaKe** [37iOS/iChatGPT#7]
<img width="404" alt="image" src="https://user-images.githubusercontent.com/16526785/218984689-2f7f7627-7241-4391-8a0e-2b3bf2eaf56a.png">

**Comment by crazypoo** [comment]
> <img alt="image" width="404" src="https://user-images.githubusercontent.com/16526785/218984689-2f7f7627-7241-4391-8a0e-2b3bf2eaf56a.png">

用這個: https://github.com/crazypoo/PTChatGPT

**Comment by iHTCboy** [comment]
@XiaBaKe  你好，目前 2.0 版本已经支持 OpenAI API key，欢迎下载 https://github.com/37iOS/iChatGPT/releases
