### ISSUE TITLE
HTTP 403 Error

### ISSUE THREAD

**Issue by AalHrum** [37iOS/iChatGPT#8]
Getting the same error 403 when sending any message even after doing the mentioned steps.
Any fix for that yet?
Thanks

**Comment by crazypoo** [comment]
> Getting the same error 403 when sending any message even after doing the mentioned steps. Any fix for that yet? Thanks

https://github.com/crazypoo/PTChatGPT

**Comment by iHTCboy** [comment]
@AalHrum  Hello, the current version 2.0 already supports OpenAI API key. Welcome to download： https://github.com/37iOS/iChatGPT/releases
