### ISSUE TITLE
The chatgpt API has been released, are there any plans to follow up

### ISSUE THREAD

**Issue by buhe** [37iOS/iChatGPT#9]
Hi there,
The chatgpt API has been released, are there any plans to follow up.

Thanks
buhe

**Comment by crazypoo** [comment]
> Hi there, The chatgpt API has been released, are there any plans to follow up.
> 
> Thanks buhe

https://github.com/crazypoo/PTChatGPT

**Comment by crazypoo** [comment]
> Hi there, The chatgpt API has been released, are there any plans to follow up.
> 
> Thanks buhe

https://github.com/crazypoo/PTChatGPT

**Comment by iHTCboy** [comment]
@buhe  Hello, the current version 2.0 already supports OpenAI API key. Welcome to download： https://github.com/37iOS/iChatGPT/releases
